In [12]:
from scipy.integrate import quad, dblquad
import numpy as np
import math

In [13]:
def psi1(x):
    return 1 - x
def psi2(x):
    return x

In [14]:
flin = [psi1, psi2]

In [15]:
def phi1(x):
    return 2 * (x - 0.5) * (x - 1)
def phi2(x):
    return -4 * x * (x - 1)
def phi3(x):
    return 2 * x * (x - 0.5)

def dphi1dx(x):
    return 4 * x - 3
def dphi2dx(x):
    return -8 * x + 4
def dphi3dx(x):
    return 4 * x - 1

In [16]:
fquad = [phi1, phi2, phi3]
dfquaddx = [dphi1dx, dphi2dx, dphi3dx]

In [17]:
Gl = np.zeros((4, 9, 9))
Gr = np.zeros((4, 9, 9))

for s in range(4):
    for i in range(9):
        for j in range(9):
            f = lambda x, y: flin[s % 2](x) * flin[s // 2](y) * fquad[i // 3](x) * dfquaddx[i % 3](y) * fquad[j // 3](x) * dfquaddx[j % 3](y)
            Gl[s][i][j] = dblquad(f, 0, 1, 0, 1)[0]

            f = lambda x, y: flin[s % 2](x) * flin[s // 2](y) * dfquaddx[i // 3](x) * fquad[i % 3](y) * dfquaddx[j // 3](x) * fquad[j % 3](y)
            Gr[s][i][j] = dblquad(f, 0, 1, 0, 1)[0]

In [18]:
def out(file_name, mat):
    with open(file_name, "w") as f:
    	for i in range(9):
    	    f.write(str(mat[i][i]))
    	    f.write(" ")
    	f.write("\n")
    	for i in range(9):
            for j in range(i):
                f.write(str(mat[i][j]))
                f.write(" ")

In [19]:
out("data/Gl0.txt", Gl[0] * 90)
out("data/Gl1.txt", Gl[1] * 90)
out("data/Gl2.txt", Gl[2] * 90)
out("data/Gl3.txt", Gl[3] * 90)

out("data/Gr0.txt", Gr[0] * 90)
out("data/Gr1.txt", Gr[1] * 90)
out("data/Gr2.txt", Gr[2] * 90)
out("data/Gr3.txt", Gr[3] * 90)

In [20]:
print((Gr[0] + Gr[1] + Gr[2] + Gr[3]) * 90)

[[  28.   14.   -7.  -32.  -16.    8.    4.    2.   -1.]
 [  14.  112.   14.  -16. -128.  -16.    2.   16.    2.]
 [  -7.   14.   28.    8.  -16.  -32.   -1.    2.    4.]
 [ -32.  -16.    8.   64.   32.  -16.  -32.  -16.    8.]
 [ -16. -128.  -16.   32.  256.   32.  -16. -128.  -16.]
 [   8.  -16.  -32.  -16.   32.   64.    8.  -16.  -32.]
 [   4.    2.   -1.  -32.  -16.    8.   28.   14.   -7.]
 [   2.   16.    2.  -16. -128.  -16.   14.  112.   14.]
 [  -1.    2.    4.    8.  -16.  -32.   -7.   14.   28.]]


In [21]:
print((Gl[0] + Gl[1] + Gl[2] + Gl[3]) * 90)

[[  28.  -32.    4.   14.  -16.    2.   -7.    8.   -1.]
 [ -32.   64.  -32.  -16.   32.  -16.    8.  -16.    8.]
 [   4.  -32.   28.    2.  -16.   14.   -1.    8.   -7.]
 [  14.  -16.    2.  112. -128.   16.   14.  -16.    2.]
 [ -16.   32.  -16. -128.  256. -128.  -16.   32.  -16.]
 [   2.  -16.   14.   16. -128.  112.    2.  -16.   14.]
 [  -7.    8.   -1.   14.  -16.    2.   28.  -32.    4.]
 [   8.  -16.    8.  -16.   32.  -16.  -32.   64.  -32.]
 [  -1.    8.   -7.    2.  -16.   14.    4.  -32.   28.]]


In [22]:
print((Gl[0] + Gl[1] + Gl[2] + Gl[3] + Gr[0] + Gr[1] + Gr[2] + Gr[3]) * 90)

[[ 5.60000000e+01 -1.80000000e+01 -3.00000000e+00 -1.80000000e+01
  -3.20000000e+01  1.00000000e+01 -3.00000000e+00  1.00000000e+01
  -2.00000000e+00]
 [-1.80000000e+01  1.76000000e+02 -1.80000000e+01 -3.20000000e+01
  -9.60000000e+01 -3.20000000e+01  1.00000000e+01  6.24500451e-16
   1.00000000e+01]
 [-3.00000000e+00 -1.80000000e+01  5.60000000e+01  1.00000000e+01
  -3.20000000e+01 -1.80000000e+01 -2.00000000e+00  1.00000000e+01
  -3.00000000e+00]
 [-1.80000000e+01 -3.20000000e+01  1.00000000e+01  1.76000000e+02
  -9.60000000e+01  1.24900090e-15 -1.80000000e+01 -3.20000000e+01
   1.00000000e+01]
 [-3.20000000e+01 -9.60000000e+01 -3.20000000e+01 -9.60000000e+01
   5.12000000e+02 -9.60000000e+01 -3.20000000e+01 -9.60000000e+01
  -3.20000000e+01]
 [ 1.00000000e+01 -3.20000000e+01 -1.80000000e+01  1.24900090e-15
  -9.60000000e+01  1.76000000e+02  1.00000000e+01 -3.20000000e+01
  -1.80000000e+01]
 [-3.00000000e+00  1.00000000e+01 -2.00000000e+00 -1.80000000e+01
  -3.20000000e+01  1.0000000